# Generated by Django 4.2 on 2024-02-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_gallery_options_size_dimensions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='dimensions',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.AddField(
            model_name='size',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
