# Generated by Django 4.2 on 2024-03-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_wishlist_review_productfaq_notification_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Review',
            new_name='review',
        ),
    ]
