# Generated by Django 4.2 on 2024-06-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_material_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
